### ISSUE TITLE
IE 11 - Syntax error when using...

### ISSUE THREAD

**Issue by dragos199993** [frogbob/vue-tilt.js#1]
IE 11 - Syntax error when using...

**Comment by vanderb** [comment]
Thanks for the reporting. This it not a bug from this wrapper-plugin itself but a bug of the vanilla-tilt.js-script.

(Ok, in my opinion the real bug is the IE itself, but thats another story 🤣)

I've added a polyfill for this. Pleas update to Version 1.0.2.

**Comment by CallumMitchellRV** [comment]
I am still experiencing this issue on 1.7.0

**Comment by vanderb** [comment]
Thats possible, yes. I do not know if the contributors of vanilla-js-script implementing this polyfill.
