### ISSUE TITLE
having trouble with easing: 

### ISSUE THREAD

**Issue by akinhwan** [frogbob/vue-tilt.js#2]
could you show an example of setting the easing param in v-tilt?

i tried v-tilt=`"{easing: "cubic-bezier(.03,.98,.52,.99)"}"` as a string but getting error

**Comment by vanderb** [comment]
Hi, you used double-quotes 2 times. That will escape your cubic-bezier-settings.
Try
`v-tilt="{easing: 'cubic-bezier(.03,.98,.52,.99')}"`
If this error still exists, please let me know
